import Head from "next/head";
import {
  CheckCircleIcon,
  ExclamationCircleIcon,
} from "@heroicons/react/24/outline";
import { ChangeEvent, useState } from "react";

const Home = () => {
  const onChange = (event: ChangeEvent<HTMLTextAreaElement>) => {
    try {
      const parsedPackageJSON = JSON.parse(event.target.value);
      if (!("dependencies" in parsedPackageJSON)) {
        setValidationStatus("invalid");
        return;
      }
      setValidationStatus("valid");
    } catch {
      setValidationStatus("invalid");
    }
  };

  const [validationStatus, setValidationStatus] = useState<
    "valid" | "invalid" | null
  >(null);

  const valid = validationStatus === "valid";
  const invalid = validationStatus === "invalid";

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={"p-4"}>
          <div>
            <label
              htmlFor="json"
              className="block text-sm font-medium text-gray-700"
            >
              Paste your package.json here
            </label>
            <div className="mt-1">
              <textarea
                onChange={onChange}
                id="json"
                name="json"
                rows={12}
                className="mt-1 p-2 block w-full rounded-md border-2 border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-indigo-500 sm:text-sm"
                placeholder="package.json"
              />
            </div>
            <div className={"flex mt-2 items-center"}>
              {valid && (
                <>
                  <CheckCircleIcon className="h-6 w-6 text-green-600" />
                  <p className="text-sm text-gray-500">Valid</p>
                </>
              )}
              {invalid && (
                <>
                  <ExclamationCircleIcon className="h-6 w-6 text-red-600" />
                  <p className="text-sm text-gray-500">Invalid</p>
                </>
              )}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
